spring:
  application:
    name: BankApplication

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG
